### ISSUE TITLE
Issue-Refactor AI page component

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#109]
Automated Review Comments
Issues in src/app/dashboard/ai/page.tsx:
  - (5, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
