### ISSUE TITLE
Issue-started working with AI

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#115]
Automated Review Comments
Issues in src/app/api/controller/hashmind.controller.ts:
  - (1, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
Issues in src/app/api/data/ai/info.ts:
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
Issues in src/app/api/functions/identifyAction.ts:
  - (19, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
Issues in src/app/api/services/tts.service.ts:
  - (2, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
Issues in src/app/api/utils/genConversation.ts:
  - (7, 'Hardcoded string found')
  - (28, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
