### ISSUE TITLE
Issue-added support for tts and stt

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#117]
Automated Review Comments
Issues in src/app/api/controller/hashmind.controller.ts:
  - (5, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/app/api/recognition/tts/route.ts:
  - (25, 'Hardcoded string found')
Issues in src/app/api/services/tts.service.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
Issues in src/app/dashboard/ai/page.tsx:
  - (50, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
Issues in src/app/gen-resp/page.tsx:
  - (15, 'Hardcoded string found')
  - (23, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
