### ISSUE TITLE
Issue-Add inngest package and implement article creation and update background jobs events

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#123]
Automated Review Comments
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/app/api/config/inngest_client.ts:
  - (2, 'Hardcoded string found')
Issues in src/app/api/controller/hashmind.controller.ts:
  - (12, 'Hardcoded string found')
Issues in src/app/api/inngest/route.ts:
  - (4, 'Line exceeds 80 characters')
Issues in yarn.lock:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (122, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (133, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (150, 'Line exceeds 80 characters')
  - (163, 'Line exceeds 80 characters')
  - (164, 'Line exceeds 80 characters')
  - (168, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (176, 'Line exceeds 80 characters')
  - (183, 'Line exceeds 80 characters')
  - (184, 'Line exceeds 80 characters')
  - (188, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (194, 'Line exceeds 80 characters')
  - (196, 'Hardcoded string found')
  - (213, 'Line exceeds 80 characters')
  - (214, 'Line exceeds 80 characters')
  - (218, 'Line exceeds 80 characters')
  - (219, 'Line exceeds 80 characters')
  - (225, 'Line exceeds 80 characters')
  - (226, 'Line exceeds 80 characters')
  - (230, 'Line exceeds 80 characters')
  - (232, 'Line exceeds 80 characters')
  - (233, 'Line exceeds 80 characters')
  - (237, 'Line exceeds 80 characters')
  - (238, 'Line exceeds 80 characters')
  - (242, 'Line exceeds 80 characters')
  - (249, 'Line exceeds 80 characters')
  - (250, 'Line exceeds 80 characters')
  - (254, 'Line exceeds 80 characters')
  - (255, 'Line exceeds 80 characters')
  - (259, 'Line exceeds 80 characters')
  - (261, 'Line exceeds 80 characters')
  - (262, 'Line exceeds 80 characters')
  - (267, 'Line exceeds 80 characters')
  - (268, 'Line exceeds 80 characters')
  - (272, 'Line exceeds 80 characters')
  - (273, 'Line exceeds 80 characters')
  - (275, 'Line exceeds 80 characters')
  - (276, 'Line exceeds 80 characters')
  - (281, 'Line exceeds 80 characters')
  - (282, 'Line exceeds 80 characters')
  - (286, 'Line exceeds 80 characters')
  - (287, 'Line exceeds 80 characters')
  - (289, 'Line exceeds 80 characters')
  - (290, 'Line exceeds 80 characters')
  - (294, 'Line exceeds 80 characters')
  - (295, 'Line exceeds 80 characters')
  - (299, 'Line exceeds 80 characters')
  - (301, 'Line exceeds 80 characters')
  - (302, 'Line exceeds 80 characters')
  - (306, 'Line exceeds 80 characters')
  - (307, 'Line exceeds 80 characters')
  - (311, 'Line exceeds 80 characters')
  - (318, 'Line exceeds 80 characters')
  - (319, 'Line exceeds 80 characters')
  - (323, 'Line exceeds 80 characters')
  - (330, 'Line exceeds 80 characters')
  - (331, 'Line exceeds 80 characters')
  - (337, 'Line exceeds 80 characters')
  - (344, 'Line exceeds 80 characters')
  - (345, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (358, 'Line exceeds 80 characters')
  - (359, 'Line exceeds 80 characters')
  - (367, 'Line exceeds 80 characters')
  - (369, 'Line exceeds 80 characters')
  - (370, 'Line exceeds 80 characters')
  - (374, 'Line exceeds 80 characters')
  - (375, 'Line exceeds 80 characters')
  - (379, 'Line exceeds 80 characters')
  - (380, 'Line exceeds 80 characters')
  - (387, 'Line exceeds 80 characters')
  - (388, 'Line exceeds 80 characters')
  - (392, 'Line exceeds 80 characters')
  - (393, 'Line exceeds 80 characters')
  - (397, 'Line exceeds 80 characters')
  - (398, 'Line exceeds 80 characters')
  - (402, 'Line exceeds 80 characters')
  - (403, 'Line exceeds 80 characters')
  - (407, 'Line exceeds 80 characters')
  - (408, 'Line exceeds 80 characters')
  - (418, 'Line exceeds 80 characters')
  - (419, 'Line exceeds 80 characters')
  - (423, 'Line exceeds 80 characters')
  - (425, 'Line exceeds 80 characters')
  - (426, 'Line exceeds 80 characters')
  - (431, 'Line exceeds 80 characters')
  - (432, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
