### ISSUE TITLE
Issue-Add event schemas and send article creation event

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#125]
Automated Review Comments
Issues in src/app/api/config/inngest_client.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in src/app/api/controller/hashmind.controller.ts:
  - (19, 'Line exceeds 80 characters')
Issues in src/app/api/jobs/inngest/functions.ts:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
