### ISSUE TITLE
Issue-Add article generation functions and update main function

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#127]
Automated Review Comments
Issues in plan.md:
  - (3, 'Line exceeds 80 characters')
Issues in src/app/api/config/inngest_client.ts:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
Issues in src/app/api/controller/hashmind.controller.ts:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in src/app/api/inngest/route.ts:
  - (4, 'Line exceeds 80 characters')
Issues in src/app/api/jobs/inngest/functions.ts:
  - (15, 'Hardcoded string found')
  - (66, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
