### ISSUE TITLE
Issue-Add job queues and subqueues for article processing

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#129]
Automated Review Comments
Issues in src/app/api/controller/hashmind.controller.ts:
  - (6, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
Issues in src/app/api/jobs/inngest/functions.ts:
  - (1, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
