### ISSUE TITLE
Issue-Add error handling and update job queue status for cover image generation

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#133]
Automated Review Comments
Issues in src/app/api/jobs/inngest/functions.ts:
  - (10, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
