### ISSUE TITLE
Issue-Add publish article function

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#137]
Automated Review Comments
Issues in src/app/api/config/inngest_client.ts:
  - (1, 'Line exceeds 80 characters')
  - (1, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
