### ISSUE TITLE
Issue-Add @radix-ui/react-switch dependency and remove formatting excellence from plan.md

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#20]
Automated Review Comments
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in plan.md:
  - (3, 'Line exceeds 80 characters')
Issues in src/app/dashboard/settings/page.tsx:
  - (25, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (190, 'Line exceeds 80 characters')
  - (204, 'Line exceeds 80 characters')
  - (218, 'Hardcoded string found')
  - (219, 'Line exceeds 80 characters')
  - (229, 'Hardcoded string found')
Issues in src/components/ui/switch.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
Issues in src/data/gpt.ts:
  - (8, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
Issues in src/lib/utils.ts:
  - (1, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in yarn.lock:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (92, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
