### ISSUE TITLE
Issue-Add audio_responses to GPT_RESP_STYLE_TYPE and import Toaster component

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#32]
Automated Review Comments
Issues in src/app/gen-resp/page.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
Issues in src/components/modules/settings/BlogStyle.tsx:
  - (45, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
Issues in src/components/modules/settings/StyleInfo.tsx:
  - (8, 'Hardcoded string found')
  - (198, 'Line exceeds 80 characters')
  - (198, 'Hardcoded string found')
  - (275, 'Line exceeds 80 characters')
  - (275, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (324, 'Line exceeds 80 characters')
  - (327, 'Hardcoded string found')
Issues in src/data/gpt.ts:
  - (11, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (31, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
