### ISSUE TITLE
Issue-Update tsconfig.json and layout.tsx, delete globals.css, and modify package.json and tailwind.config.ts

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#6]
Automated Review Comments
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
Issues in src/app/layout.tsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
Issues in src/app/page.tsx:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
Issues in src/components/ui/button.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
Issues in src/components/ui/input.tsx:
  - (2, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
Issues in src/config/font.ts:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
Issues in src/lib/utils.ts:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in tailwind.config.ts:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in tsconfig.json:
  - (4, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in yarn.lock:
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (122, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (150, 'Line exceeds 80 characters')
  - (151, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (156, 'Line exceeds 80 characters')
  - (158, 'Hardcoded string found')
  - (159, 'Line exceeds 80 characters')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (165, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (168, 'Hardcoded string found')
  - (169, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (174, 'Line exceeds 80 characters')
  - (175, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
  - (181, 'Line exceeds 80 characters')
  - (182, 'Line exceeds 80 characters')
  - (188, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (194, 'Line exceeds 80 characters')
  - (196, 'Hardcoded string found')
  - (200, 'Line exceeds 80 characters')
  - (201, 'Line exceeds 80 characters')
  - (207, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (212, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (215, 'Hardcoded string found')
  - (219, 'Line exceeds 80 characters')
  - (220, 'Line exceeds 80 characters')
  - (222, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (228, 'Line exceeds 80 characters')
  - (229, 'Line exceeds 80 characters')
  - (233, 'Line exceeds 80 characters')
  - (234, 'Line exceeds 80 characters')
  - (238, 'Line exceeds 80 characters')
  - (239, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (244, 'Line exceeds 80 characters')
  - (250, 'Line exceeds 80 characters')
  - (251, 'Line exceeds 80 characters')
  - (255, 'Line exceeds 80 characters')
  - (256, 'Line exceeds 80 characters')
  - (260, 'Line exceeds 80 characters')
  - (261, 'Line exceeds 80 characters')
  - (268, 'Line exceeds 80 characters')
  - (269, 'Line exceeds 80 characters')
  - (273, 'Line exceeds 80 characters')
  - (274, 'Line exceeds 80 characters')
  - (278, 'Line exceeds 80 characters')
  - (279, 'Line exceeds 80 characters')
  - (290, 'Line exceeds 80 characters')
  - (291, 'Line exceeds 80 characters')
  - (299, 'Line exceeds 80 characters')
  - (300, 'Line exceeds 80 characters')
  - (304, 'Line exceeds 80 characters')
  - (305, 'Line exceeds 80 characters')
  - (309, 'Line exceeds 80 characters')
  - (310, 'Line exceeds 80 characters')
  - (316, 'Line exceeds 80 characters')
  - (317, 'Line exceeds 80 characters')
  - (323, 'Line exceeds 80 characters')
  - (324, 'Line exceeds 80 characters')
  - (333, 'Line exceeds 80 characters')
  - (334, 'Line exceeds 80 characters')
  - (340, 'Line exceeds 80 characters')
  - (341, 'Line exceeds 80 characters')
  - (343, 'Line exceeds 80 characters')
  - (345, 'Line exceeds 80 characters')
  - (346, 'Line exceeds 80 characters')
  - (350, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (365, 'Line exceeds 80 characters')
  - (366, 'Line exceeds 80 characters')
  - (372, 'Line exceeds 80 characters')
  - (373, 'Line exceeds 80 characters')
  - (377, 'Line exceeds 80 characters')
  - (378, 'Line exceeds 80 characters')
  - (382, 'Line exceeds 80 characters')
  - (383, 'Line exceeds 80 characters')
  - (387, 'Line exceeds 80 characters')
  - (388, 'Line exceeds 80 characters')
  - (394, 'Line exceeds 80 characters')
  - (395, 'Line exceeds 80 characters')
  - (399, 'Line exceeds 80 characters')
  - (400, 'Line exceeds 80 characters')
  - (406, 'Line exceeds 80 characters')
  - (407, 'Line exceeds 80 characters')
  - (411, 'Line exceeds 80 characters')
  - (412, 'Line exceeds 80 characters')
  - (420, 'Line exceeds 80 characters')
  - (421, 'Line exceeds 80 characters')
  - (425, 'Line exceeds 80 characters')
  - (426, 'Line exceeds 80 characters')
  - (430, 'Line exceeds 80 characters')
  - (431, 'Line exceeds 80 characters')
  - (435, 'Line exceeds 80 characters')
  - (436, 'Line exceeds 80 characters')
  - (440, 'Line exceeds 80 characters')
  - (441, 'Line exceeds 80 characters')
  - (445, 'Line exceeds 80 characters')
  - (446, 'Line exceeds 80 characters')
  - (450, 'Line exceeds 80 characters')
  - (451, 'Line exceeds 80 characters')
  - (455, 'Line exceeds 80 characters')
  - (456, 'Line exceeds 80 characters')
  - (460, 'Line exceeds 80 characters')
  - (461, 'Line exceeds 80 characters')
  - (465, 'Line exceeds 80 characters')
  - (466, 'Line exceeds 80 characters')
  - (470, 'Line exceeds 80 characters')
  - (471, 'Line exceeds 80 characters')
  - (475, 'Line exceeds 80 characters')
  - (476, 'Line exceeds 80 characters')
  - (478, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (486, 'Line exceeds 80 characters')
  - (487, 'Line exceeds 80 characters')
  - (493, 'Line exceeds 80 characters')
  - (494, 'Line exceeds 80 characters')
  - (500, 'Line exceeds 80 characters')
  - (501, 'Line exceeds 80 characters')
  - (505, 'Line exceeds 80 characters')
  - (506, 'Line exceeds 80 characters')
  - (513, 'Line exceeds 80 characters')
  - (514, 'Line exceeds 80 characters')
  - (522, 'Line exceeds 80 characters')
  - (523, 'Line exceeds 80 characters')
  - (527, 'Line exceeds 80 characters')
  - (528, 'Line exceeds 80 characters')
  - (532, 'Line exceeds 80 characters')
  - (533, 'Line exceeds 80 characters')
  - (537, 'Line exceeds 80 characters')
  - (538, 'Line exceeds 80 characters')
  - (544, 'Line exceeds 80 characters')
  - (545, 'Line exceeds 80 characters')
  - (551, 'Line exceeds 80 characters')
  - (552, 'Line exceeds 80 characters')
  - (556, 'Line exceeds 80 characters')
  - (557, 'Line exceeds 80 characters')
  - (567, 'Line exceeds 80 characters')
  - (568, 'Line exceeds 80 characters')
  - (572, 'Line exceeds 80 characters')
  - (573, 'Line exceeds 80 characters')
  - (577, 'Line exceeds 80 characters')
  - (578, 'Line exceeds 80 characters')
  - (584, 'Line exceeds 80 characters')
  - (585, 'Line exceeds 80 characters')
  - (591, 'Line exceeds 80 characters')
  - (592, 'Line exceeds 80 characters')
  - (598, 'Line exceeds 80 characters')
  - (599, 'Line exceeds 80 characters')
  - (603, 'Line exceeds 80 characters')
  - (604, 'Line exceeds 80 characters')
  - (608, 'Line exceeds 80 characters')
  - (609, 'Line exceeds 80 characters')
  - (615, 'Line exceeds 80 characters')
  - (616, 'Line exceeds 80 characters')
  - (620, 'Line exceeds 80 characters')
  - (621, 'Line exceeds 80 characters')
  - (625, 'Line exceeds 80 characters')
  - (626, 'Line exceeds 80 characters')
  - (628, 'Hardcoded string found')
  - (630, 'Hardcoded string found')
  - (634, 'Line exceeds 80 characters')
  - (635, 'Line exceeds 80 characters')
  - (639, 'Line exceeds 80 characters')
  - (640, 'Line exceeds 80 characters')
  - (644, 'Line exceeds 80 characters')
  - (645, 'Line exceeds 80 characters')
  - (649, 'Line exceeds 80 characters')
  - (650, 'Line exceeds 80 characters')
  - (654, 'Line exceeds 80 characters')
  - (655, 'Line exceeds 80 characters')
  - (659, 'Line exceeds 80 characters')
  - (660, 'Line exceeds 80 characters')
  - (666, 'Line exceeds 80 characters')
  - (667, 'Line exceeds 80 characters')
  - (671, 'Line exceeds 80 characters')
  - (672, 'Line exceeds 80 characters')
  - (676, 'Line exceeds 80 characters')
  - (677, 'Line exceeds 80 characters')
  - (681, 'Line exceeds 80 characters')
  - (682, 'Line exceeds 80 characters')
  - (689, 'Line exceeds 80 characters')
  - (690, 'Line exceeds 80 characters')
  - (694, 'Line exceeds 80 characters')
  - (695, 'Line exceeds 80 characters')
  - (701, 'Line exceeds 80 characters')
  - (702, 'Line exceeds 80 characters')
  - (708, 'Line exceeds 80 characters')
  - (709, 'Line exceeds 80 characters')
  - (713, 'Line exceeds 80 characters')
  - (714, 'Line exceeds 80 characters')
  - (722, 'Line exceeds 80 characters')
  - (723, 'Line exceeds 80 characters')
  - (727, 'Line exceeds 80 characters')
  - (728, 'Line exceeds 80 characters')
  - (732, 'Line exceeds 80 characters')
  - (733, 'Line exceeds 80 characters')
  - (735, 'Hardcoded string found')
  - (736, 'Hardcoded string found')
  - (744, 'Hardcoded string found')
  - (745, 'Hardcoded string found')
  - (746, 'Hardcoded string found')
  - (747, 'Hardcoded string found')
  - (748, 'Hardcoded string found')
  - (749, 'Hardcoded string found')
  - (750, 'Hardcoded string found')
  - (751, 'Hardcoded string found')
  - (752, 'Hardcoded string found')
  - (756, 'Line exceeds 80 characters')
  - (757, 'Line exceeds 80 characters')
  - (761, 'Line exceeds 80 characters')
  - (762, 'Line exceeds 80 characters')
  - (766, 'Line exceeds 80 characters')
  - (767, 'Line exceeds 80 characters')
  - (771, 'Line exceeds 80 characters')
  - (772, 'Line exceeds 80 characters')
  - (776, 'Line exceeds 80 characters')
  - (777, 'Line exceeds 80 characters')
  - (781, 'Line exceeds 80 characters')
  - (782, 'Line exceeds 80 characters')
  - (786, 'Line exceeds 80 characters')
  - (787, 'Line exceeds 80 characters')
  - (791, 'Line exceeds 80 characters')
  - (792, 'Line exceeds 80 characters')
  - (799, 'Line exceeds 80 characters')
  - (800, 'Line exceeds 80 characters')
  - (804, 'Line exceeds 80 characters')
  - (805, 'Line exceeds 80 characters')
  - (809, 'Line exceeds 80 characters')
  - (810, 'Line exceeds 80 characters')
  - (814, 'Line exceeds 80 characters')
  - (815, 'Line exceeds 80 characters')
  - (819, 'Line exceeds 80 characters')
  - (820, 'Line exceeds 80 characters')
  - (828, 'Line exceeds 80 characters')
  - (829, 'Line exceeds 80 characters')
  - (835, 'Line exceeds 80 characters')
  - (836, 'Line exceeds 80 characters')
  - (843, 'Line exceeds 80 characters')
  - (844, 'Line exceeds 80 characters')
  - (850, 'Line exceeds 80 characters')
  - (851, 'Line exceeds 80 characters')
  - (858, 'Line exceeds 80 characters')
  - (859, 'Line exceeds 80 characters')
  - (863, 'Line exceeds 80 characters')
  - (864, 'Line exceeds 80 characters')
  - (872, 'Line exceeds 80 characters')
  - (873, 'Line exceeds 80 characters')
  - (881, 'Line exceeds 80 characters')
  - (882, 'Line exceeds 80 characters')
  - (884, 'Hardcoded string found')
  - (888, 'Line exceeds 80 characters')
  - (889, 'Line exceeds 80 characters')
  - (893, 'Line exceeds 80 characters')
  - (894, 'Line exceeds 80 characters')
  - (898, 'Line exceeds 80 characters')
  - (899, 'Line exceeds 80 characters')
  - (906, 'Line exceeds 80 characters')
  - (907, 'Line exceeds 80 characters')
  - (913, 'Line exceeds 80 characters')
  - (914, 'Line exceeds 80 characters')
  - (920, 'Line exceeds 80 characters')
  - (921, 'Line exceeds 80 characters')
  - (927, 'Line exceeds 80 characters')
  - (928, 'Line exceeds 80 characters')
  - (934, 'Line exceeds 80 characters')
  - (935, 'Line exceeds 80 characters')
  - (939, 'Line exceeds 80 characters')
  - (940, 'Line exceeds 80 characters')
  - (948, 'Line exceeds 80 characters')
  - (949, 'Line exceeds 80 characters')
  - (953, 'Line exceeds 80 characters')
  - (954, 'Line exceeds 80 characters')
  - (960, 'Line exceeds 80 characters')
  - (961, 'Line exceeds 80 characters')
  - (967, 'Line exceeds 80 characters')
  - (968, 'Line exceeds 80 characters')
  - (974, 'Line exceeds 80 characters')
  - (975, 'Line exceeds 80 characters')
  - (979, 'Line exceeds 80 characters')
  - (980, 'Line exceeds 80 characters')
  - (984, 'Line exceeds 80 characters')
  - (985, 'Line exceeds 80 characters')
  - (989, 'Line exceeds 80 characters')
  - (990, 'Line exceeds 80 characters')
  - (995, 'Line exceeds 80 characters')
  - (996, 'Line exceeds 80 characters')
  - (1004, 'Line exceeds 80 characters')
  - (1005, 'Line exceeds 80 characters')
  - (1014, 'Line exceeds 80 characters')
  - (1015, 'Line exceeds 80 characters')
  - (1021, 'Line exceeds 80 characters')
  - (1022, 'Line exceeds 80 characters')
  - (1028, 'Line exceeds 80 characters')
  - (1029, 'Line exceeds 80 characters')
  - (1035, 'Line exceeds 80 characters')
  - (1036, 'Line exceeds 80 characters')
  - (1038, 'Hardcoded string found')
  - (1048, 'Line exceeds 80 characters')
  - (1049, 'Line exceeds 80 characters')
  - (1053, 'Line exceeds 80 characters')
  - (1054, 'Line exceeds 80 characters')
  - (1056, 'Hardcoded string found')
  - (1060, 'Line exceeds 80 characters')
  - (1061, 'Line exceeds 80 characters')
  - (1065, 'Line exceeds 80 characters')
  - (1066, 'Line exceeds 80 characters')
  - (1068, 'Hardcoded string found')
  - (1093, 'Line exceeds 80 characters')
  - (1094, 'Line exceeds 80 characters')
  - (1100, 'Line exceeds 80 characters')
  - (1101, 'Line exceeds 80 characters')
  - (1107, 'Line exceeds 80 characters')
  - (1108, 'Line exceeds 80 characters')
  - (1114, 'Line exceeds 80 characters')
  - (1115, 'Line exceeds 80 characters')
  - (1119, 'Line exceeds 80 characters')
  - (1120, 'Line exceeds 80 characters')
  - (1124, 'Line exceeds 80 characters')
  - (1125, 'Line exceeds 80 characters')
  - (1129, 'Line exceeds 80 characters')
  - (1130, 'Line exceeds 80 characters')
  - (1134, 'Line exceeds 80 characters')
  - (1135, 'Line exceeds 80 characters')
  - (1142, 'Line exceeds 80 characters')
  - (1143, 'Line exceeds 80 characters')
  - (1147, 'Line exceeds 80 characters')
  - (1148, 'Line exceeds 80 characters')
  - (1155, 'Line exceeds 80 characters')
  - (1156, 'Line exceeds 80 characters')
  - (1162, 'Line exceeds 80 characters')
  - (1163, 'Line exceeds 80 characters')
  - (1171, 'Line exceeds 80 characters')
  - (1172, 'Line exceeds 80 characters')
  - (1180, 'Line exceeds 80 characters')
  - (1181, 'Line exceeds 80 characters')
  - (1185, 'Line exceeds 80 characters')
  - (1186, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
