### ISSUE TITLE
Issue-Update global styles and tsconfig paths

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#8]
Automated Review Comments
Issues in src/app/dashboard/ai/page.tsx:
  - (2, 'Hardcoded string found')
Issues in src/app/dashboard/home/page.tsx:
  - (2, 'Hardcoded string found')
Issues in src/app/dashboard/layout.tsx:
  - (3, 'Hardcoded string found')
Issues in src/app/dashboard/settings/page.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/flex.tsx:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
Issues in src/components/navigations/toolbar.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
Issues in tsconfig.json:
  - (3, 'Hardcoded string found')
  - (10, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
