### ISSUE TITLE
Issue-Add Svix headers to webhook verification

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#86]
Automated Review Comments
Issues in src/app/api/webhook/clerk/route.ts:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
Issues in src/prisma/schema.prisma:
  - (6, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
