### ISSUE TITLE
Issue-Add UserButton component and detect user's time of day

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#90]
Automated Review Comments
Issues in src/app/dashboard/home/page.tsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in src/components/loader.tsx:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
