### ISSUE TITLE
Issue-Add react-speech-recognition package and update types

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/hashmind1#99]
Automated Review Comments
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in plan.md:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
Issues in src/app/api/data/ai/info.ts:
  - (3, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
Issues in src/app/dashboard/ai/page.tsx:
  - (10, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
Issues in src/hooks/useSpeechRecognition.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
Issues in src/prisma/schema.prisma:
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in yarn.lock:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
